version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.12"

python:
  install:
    - requirements: docs/ci-requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - dev
