version: 2

sphinx:
  configuration: docs/source/conf.py

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.14"
  apt_packages:
    - libgvplugin-neato-layout8
  jobs:
    post_install:
      - kaleido_get_chrome

python:
  install:
    - requirements: docs/ci-requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - dev
        - docs
