from pathlib import Path

import numpy as np
try:
    from ultralytics import YOLO
except ImportError as error:
    raise ImportError(
        "Usage of the Ultralytics detectors requires that the optional package dependency "
        "'ultralytics' is installed. This can be achieved by running "
        "'python -m pip install stonesoup[ultralytics]'")\
        from error

from ._video import _VideoAsyncBoxDetector
from ..base import Property
from ..types.array import StateVector
from ..types.detection import Detection


class UltralyticsBoxObjectDetector(_VideoAsyncBoxDetector):
    """UltralyticsBoxObjectDetector

    A box object detector that generates detections of objects in the form of bounding boxes
    from image/video frames using an `Ultralytics <https://docs.ultralytics.com/>`_ YOLO object
    detection model.

    The detections generated by the box detector have the form of bounding boxes that capture
    the area of the frame where an object is detected. Each bounding box is represented by a
    vector of the form ``[x, y, w, h]``, where ``x, y`` denote the pixel coordinates of the
    top-left corner, while ``w, h`` denote the width and height of the bounding box.

    Additionally, each detection carries the following meta-data fields:

    - ``raw_box``: The raw bounding box containing the normalised coordinates
      ``[y_0, x_0, y_1, x_1]``.
    - ``class``: A dict with keys ``id`` and ``name`` relating to the id and name of the
      detection class.
    - ``score``: A float in the range ``(0, 1]`` indicating the detector's confidence.

    Important
    ---------
    Use of this class requires that the optional package dependency ``ultralytics`` is installed.
    This can be achieved by running ``python -m pip install stonesoup[ultralytics]``.

    """

    model_path: Path = Property(
        doc="Path to a YOLO model file (e.g. ``yolo11n.pt``). Pretrained model names are "
            "downloaded automatically by Ultralytics if a matching file is not found locally.")
    predict_kwargs: dict = Property(
        default=None,
        doc="Optional keyword arguments passed through to the model on each frame (e.g. "
            "``conf``, ``classes``, ``device``, ``imgsz``). See the `Ultralytics predict "
            "documentation <https://docs.ultralytics.com/modes/predict/>`_ for available "
            "options. Default `None`, where no additional arguments are passed.")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.predict_kwargs is None:
            self.predict_kwargs = {}
        self.model = YOLO(self.model_path)

    def _get_detections_from_frame(self, frame):
        # Perform detection. `verbose=False` suppresses Ultralytics' per-frame console output.
        results = self.model(frame.pixels, verbose=False, **self.predict_kwargs)
        result = results[0]
        names = result.names

        # Form detections
        detections = set()
        frame_height, frame_width = frame.pixels.shape[:2]
        for box in result.boxes:
            x0, y0, x1, y1 = box.xyxy[0].tolist()
            class_ = int(box.cls)
            score = float(box.conf)
            metadata = {
                "raw_box": np.array([y0 / frame_height, x0 / frame_width,
                                     y1 / frame_height, x1 / frame_width]),
                "class": {"id": class_, "name": names[class_]},
                "score": score,
            }
            # Transform box to be in format (x, y, w, h)
            state_vector = StateVector([x0, y0, x1 - x0, y1 - y0])
            detection = Detection(state_vector=state_vector,
                                  timestamp=frame.timestamp,
                                  metadata=metadata)
            detections.add(detection)

        return detections
