name: Documentation link
on: status
jobs:
  circleci_artifacts_redirector_job:
    runs-on: ubuntu-latest
    if: "${{ github.event.context == 'ci/circleci: docs' }}"
    name: Run CircleCI artifacts redirector
    steps:
      - name: GitHub Action step
        uses: larsoner/circleci-artifacts-redirector-action@0.3.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          artifact-path: 0/docs/index.html
          circleci-jobs: docs
