name: Lint

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run flake8
        uses: TrueBrain/actions-flake8@v2
        with:
          path: "stonesoup"
